#!/usr/bin/env bash

fish_history_file="$HOME/.local/share/fish/fish_history"

bash_history_file="$HOME/.bash_history

if [ ! -f "$fish_history_file" ]; then
    echo "Fish history file not found at $fish_history_file"
    exit 1
fi

if [ ! -f "$bash_history_file" ]; then
    echo "Bash history file not found at $bash_history_file"
    exit 1
fi

grep '^- cmd: ' "$fish_history_file" | sed 's/^- cmd: //g' | awk '!seen[$0]++' >>"$bash_history_file"
